// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css'
;

function renderSquare(i) {
  return React.createElement("button", {
              className: "square"
            });
}

var board = React.createElement("div", undefined, React.createElement("div", {
          className: "status"
        }, "Next player: X"), React.createElement("div", {
          className: "board-row"
        }, renderSquare(0), renderSquare(1), renderSquare(2)), React.createElement("div", {
          className: "board-row"
        }, renderSquare(3), renderSquare(4), renderSquare(5)), React.createElement("div", {
          className: "board-row"
        }, renderSquare(6), renderSquare(7), renderSquare(8)));

var game = React.createElement("div", {
      className: "game"
    }, React.createElement("div", {
          className: "game-board"
        }, board), React.createElement("div", {
          className: "game-info"
        }, "Hello2"));

function App(Props) {
  return game;
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
